wandb_version: 1

env_id:
  desc: null
  value: go_9x9
seed:
  desc: null
  value: 0
max_num_iters:
  desc: null
  value: 400
num_channels:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 6
resnet_v2:
  desc: null
  value: true
selfplay_batch_size:
  desc: null
  value: 1024
num_simulations:
  desc: null
  value: 32
max_num_steps:
  desc: null
  value: 256
training_batch_size:
  desc: null
  value: 4096
learning_rate:
  desc: null
  value: 0.001
eval_interval:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699652568.579378
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
